bugfix: add missing annotations from __future__
otherwise, Union type hint in methods fails:

File "/home/hass/.homeassistant/custom_components/yi_hack/media_player.py", line 249, in YiHackMediaPlayer
media_content_type: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'