Fix Media Player unable to play sometimes
1. response uninitialised variable
2. allow tts at the same time (2nd one will wait in acquire())
 
Traceback (most recent call last):
....
  File "/config/custom_components/yi_hack/media_player.py", line 196, in _perform_speaker
    if response is None:
UnboundLocalError: local variable 'response' referenced before assignment